/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TeamTeamIdImport } from './routes/team.$teamId'
import { Route as PokemonBattleBattleIdImport } from './routes/pokemonBattle.$battleId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamTeamIdRoute = TeamTeamIdImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRoute,
} as any)

const PokemonBattleBattleIdRoute = PokemonBattleBattleIdImport.update({
  id: '/pokemonBattle/$battleId',
  path: '/pokemonBattle/$battleId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemonBattle/$battleId': {
      id: '/pokemonBattle/$battleId'
      path: '/pokemonBattle/$battleId'
      fullPath: '/pokemonBattle/$battleId'
      preLoaderRoute: typeof PokemonBattleBattleIdImport
      parentRoute: typeof rootRoute
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemonBattle/$battleId': typeof PokemonBattleBattleIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemonBattle/$battleId': typeof PokemonBattleBattleIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pokemonBattle/$battleId': typeof PokemonBattleBattleIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemonBattle/$battleId' | '/team/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemonBattle/$battleId' | '/team/$teamId'
  id: '__root__' | '/' | '/pokemonBattle/$battleId' | '/team/$teamId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonBattleBattleIdRoute: typeof PokemonBattleBattleIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonBattleBattleIdRoute: PokemonBattleBattleIdRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pokemonBattle/$battleId",
        "/team/$teamId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pokemonBattle/$battleId": {
      "filePath": "pokemonBattle.$battleId.tsx"
    },
    "/team/$teamId": {
      "filePath": "team.$teamId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
